export const INCREMENT_TERM_SEEN_COUNT = 'INCREMENT_TERM_SEEN_COUNT';
export const POP_TERM_HISTORY = 'POP_TERM_HISTORY';
export const PUSH_ONTO_TERM_HISTORY = 'PUSH_ONTO_TERM_HISTORY';
export const RESET_SEEN_COUNTS_FOR_CATEGORY_TERMS = 'RESET_SEEN_COUNTS_FOR_CATEGORY_TERMS';
export const SET_SOUND_ENABLED = 'SET_SOUND_ENABLED';
